# Generated by Django 6.0.6 on 2026-07-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес или место')),
                ('category', models.CharField(choices=[('yard', 'Двор'), ('road', 'Дорога'), ('garbage', 'Мусор'), ('lighting', 'Освещение'), ('entrance', 'Подъезд'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Категория')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('sent', 'Отправлено'), ('resolved', 'Решено'), ('rejected', 'Отклонено')], default='new', max_length=30, verbose_name='Статус')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_public', models.BooleanField(default=False, verbose_name='Сделать публичным?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='problem_photos/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='problems.problem', verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Фото проблемы',
                'verbose_name_plural': 'Фото проблем',
            },
        ),
    ]
