# Generated by Django 6.0.6 on 2026-07-05 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='votes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Важность'),
        ),
        migrations.CreateModel(
            name='ProblemVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='problems.problem', verbose_name='Важность')),
            ],
            options={
                'verbose_name': 'Голос за проблему',
                'verbose_name_plural': 'Голоса за проблему',
                'constraints': [models.UniqueConstraint(fields=('problem', 'session_key'), name='unique_problem_vote_per_session')],
            },
        ),
    ]
