# Generated by Django 6.0.6 on 2026-07-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_votes_count_problemvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Причина отклонения'),
        ),
    ]
