# Generated by Django 6.0.6 on 2026-07-06 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='has_prior_attempts',
            field=models.BooleanField(default=False, verbose_name='Житель уже пытался решить проблему через другие инстанции'),
        ),
        migrations.CreateModel(
            name='ProblemEvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='problem_evidence/', verbose_name='Файл с ответом, отказом или отпиской')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='problems.problem', verbose_name='Проблема')),
            ],
            options={
                'verbose_name': 'Файл по предыдущему обращению',
                'verbose_name_plural': 'Файлы по предыдущим обращениям',
            },
        ),
    ]
