# Generated by Django 6.0.6 on 2026-07-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_has_prior_attempts_problemevidencefile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_public', 'status', '-created_at'], name='problem_public_status_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_public', 'status', '-votes_count', 'created_at'], name='problem_public_votes_idx'),
        ),
        migrations.AddIndex(
            model_name='problemvote',
            index=models.Index(fields=['session_key'], name='problem_vote_session_idx'),
        ),
    ]
