# Generated by Codex on 2026-07-12

from django.db import migrations

import problems.encryption
import problems.phone


def encrypt_existing_contact_phones(apps, schema_editor):
    Problem = apps.get_model("problems", "Problem")

    for problem in Problem.objects.exclude(contact_phone="").iterator():
        phone = problem.contact_phone
        problem.contact_phone = phone
        problem.save(update_fields=["contact_phone"])


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0005_problem_problem_public_status_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="contact_phone",
            field=problems.encryption.EncryptedTextField(
                blank=True,
                validators=[problems.phone.validate_russian_phone],
                verbose_name="Телефон",
            ),
        ),
        migrations.RunPython(
            encrypt_existing_contact_phones,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="problem",
            name="contact_name",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="contact_email",
        ),
    ]
