# Generated by Codex on 2026-07-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0006_encrypt_contact_phone_remove_name_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problem",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "view_problem_contact_phone",
                        "Can view decrypted problem contact phone",
                    )
                ],
                "verbose_name": "Обращение",
                "verbose_name_plural": "Обращения",
            },
        ),
    ]
